# Generated by Django 4.2.3 on 2023-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='pais',
            new_name='direccion',
        ),
    ]
